version: "3.8"
name: aims

services:
  api-gateway-proxy:
    image: nginx:alpine
    container_name: api_gateway_proxy
    ports:
      - 3002:80

    volumes:
      - ./api_gateway_proxy.nginx:/etc/nginx/conf.d/default.conf

  web-app-proxy:
    image: nginx:alpine
    container_name: web_app_proxy
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./web_app_proxy.nginx:/etc/nginx/nginx.conf:ro
      - ./aims.crt:/etc/ssl/certs/aims.crt
      - ./aims.key:/etc/ssl/private/aims.key

  account-ldap:
    image: osixia/openldap:1.2.2
    container_name: account_ldap
    restart: always
    environment:
      COMPOSE_HTTP_TIMEOUT: 200
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "aims"
      LDAP_DOMAIN: "aims.edu.co"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "aims"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_READONLY_USER: "false"
      LDAP_BACKEND: "hdb"
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "false"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-SSL3.0"
      LDAP_TLS_PROTOCOL_MIN: "3.1"
      LDAP_TLS_VERIFY_CLIENT: "demand"
      LDAP_REPLICATION: "false"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "true"
      LDAP_SSL_HELPER_PREFIX: "ldap"
    tty: true
    stdin_open: true
    volumes:
      - account_ldap_data:/var/lib/ldap
      - account_ldap_config:/etc/ldap/slapd.d
      - account_ldap_certs:/container/service/slapd/assets/certs/
    ports:
      - "389:389"
      - "636:636"
    hostname: "aims.edu.co"

volumes:
  account_ldap_data:
  account_ldap_config:
  account_ldap_certs:
