version: "3.8"
name: aims

services:
  api-gateway-proxy:
    image: nginx:alpine
    container_name: api_gateway_proxy
    ports:
      - 3002:80

    volumes:
      - ./api_gateway_proxy.nginx:/etc/nginx/conf.d/default.conf

  web-app-proxy:
    image: nginx:alpine
    container_name: web_app_proxy
    ports:
      - 80:80

    volumes:
      - ./web_app_proxy.nginx:/etc/nginx/conf.d/default.conf
